public enum WeaponType
{
    PISTOL,
    BATTLE_RIFLE,
    PRECISION_RIFLE,
    SHOTGUN,
    FLAK_CANNON,
    HOMING_LAUNCHER,
    BUSTER_LAUNCHER,
    PLASMA_RIFLE,
    RAILGUN,
    RICOCHET_REVOLVER,
    FLAMETHROWER,
    TESLA_COIL,
    CHAINGUN
}
